name: Vérification du respect des spécifications

on:
  push:
    paths:
      - 'schema.json'
      - 'exemple-valide.json'

jobs:
  validate_json:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Validate JSON with AVJ.
      uses: docker://orrosenblatt/validate-json-action:latest
      env:
        INPUT_SCHEMA: schema.json
        INPUT_JSONS: exemple-valide.json
        