name: Validate JSON

on:
  push:
    paths:
      - 'schema.json'
      - 'exemple-valide.json'
      - 'validate.yml'

jobs:
  validate_json:
    runs-on: ubuntu-latest
    steps:
      - name: build the schema and validate the data
        uses: idrissad/jsonschema_validator@v1.0
        id: validation
        with:
          main_schema_path: /../../schema.json
          additional_schemas_path: /../../GeoJSON_schemas/
          data_path: /../../exemple-valide.json
      - name: print the results
        run: echo "${{ steps.validation.outputs.validity }}"